var classes = [
    {
        "name": "Database",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getConnection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "close",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "PDO",
            "PDO"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 42,
        "vocabulary": 26,
        "volume": 197.42,
        "difficulty": 4.2,
        "effort": 829.16,
        "level": 0.24,
        "bugs": 0.07,
        "time": 46,
        "intelligentContent": 47,
        "number_operators": 14,
        "number_operands": 28,
        "number_operators_unique": 6,
        "number_operands_unique": 20,
        "cloc": 10,
        "loc": 37,
        "lloc": 27,
        "mi": 87.68,
        "mIwoC": 51.63,
        "commentWeight": 36.05,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 3,
        "package": "\\",
        "pageRank": 0.2,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "EnvLoader",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 51,
        "vocabulary": 24,
        "volume": 233.83,
        "difficulty": 7.41,
        "effort": 1733.12,
        "level": 0.13,
        "bugs": 0.08,
        "time": 96,
        "intelligentContent": 31.55,
        "number_operators": 15,
        "number_operands": 36,
        "number_operators_unique": 7,
        "number_operands_unique": 17,
        "cloc": 0,
        "loc": 28,
        "lloc": 28,
        "mi": 51.17,
        "mIwoC": 51.17,
        "commentWeight": 0,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Controllers\\AboutController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Views\\AboutTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "isAdmin",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "requireAdmin",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "log",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dashboard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clearLogs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRole",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "activate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrders",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 12,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 63,
        "ccn": 52,
        "ccnMethodMax": 13,
        "externals": [
            "Models\\Log",
            "Models\\Product",
            "Models\\User",
            "Models\\Log",
            "Views\\AdminTemplate",
            "Models\\Log",
            "Views\\AdminTemplate",
            "Models\\Log",
            "Models\\Product",
            "Models\\Product",
            "Views\\AdminTemplate",
            "Models\\Product",
            "Views\\AdminTemplate",
            "Models\\User",
            "Models\\User",
            "Models\\User",
            "Models\\Log",
            "Views\\AdminTemplate",
            "Controllers\\Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 521,
        "vocabulary": 108,
        "volume": 3519.3,
        "difficulty": 22.17,
        "effort": 78023.16,
        "level": 0.05,
        "bugs": 1.17,
        "time": 4335,
        "intelligentContent": 158.74,
        "number_operators": 130,
        "number_operands": 391,
        "number_operators_unique": 11,
        "number_operands_unique": 97,
        "cloc": 0,
        "loc": 188,
        "lloc": 188,
        "mi": 18.57,
        "mIwoC": 18.57,
        "commentWeight": 0,
        "kanDefect": 1.43,
        "relativeStructuralComplexity": 676,
        "relativeDataComplexity": 0.12,
        "relativeSystemComplexity": 676.12,
        "totalStructuralComplexity": 8112,
        "totalDataComplexity": 1.41,
        "totalSystemComplexity": 8113.41,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\AuthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "processRegister",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "processLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 15,
        "ccnMethodMax": 11,
        "externals": [
            "Views\\AuthTemplate",
            "Services\\ValidateRegisterData",
            "Models\\User",
            "Models\\Log",
            "Views\\AuthTemplate",
            "Models\\User",
            "Models\\Log"
        ],
        "parents": [],
        "implements": [],
        "lcom": 5,
        "length": 167,
        "vocabulary": 44,
        "volume": 911.73,
        "difficulty": 7.76,
        "effort": 7071.71,
        "level": 0.13,
        "bugs": 0.3,
        "time": 393,
        "intelligentContent": 117.54,
        "number_operators": 46,
        "number_operands": 121,
        "number_operators_unique": 5,
        "number_operands_unique": 39,
        "cloc": 12,
        "loc": 100,
        "lloc": 88,
        "mi": 60.4,
        "mIwoC": 34.84,
        "commentWeight": 25.56,
        "kanDefect": 0.78,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 180,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\BasketController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getStorageType",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCart",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveCart",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setStorage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 42,
        "ccn": 34,
        "ccnMethodMax": 10,
        "externals": [
            "Models\\Product",
            "Views\\BasketTemplate",
            "Models\\Log"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 266,
        "vocabulary": 58,
        "volume": 1558.22,
        "difficulty": 19.58,
        "effort": 30515.2,
        "level": 0.05,
        "bugs": 0.52,
        "time": 1695,
        "intelligentContent": 79.57,
        "number_operators": 78,
        "number_operands": 188,
        "number_operators_unique": 10,
        "number_operands_unique": 48,
        "cloc": 1,
        "loc": 136,
        "lloc": 135,
        "mi": 33.22,
        "mIwoC": 26.6,
        "commentWeight": 6.62,
        "kanDefect": 1.64,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 36.73,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 6.57,
        "totalSystemComplexity": 330.57,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\CatalogController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Models\\Product",
            "Views\\CatalogTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 4,
        "volume": 14,
        "difficulty": 2,
        "effort": 28,
        "level": 0.5,
        "bugs": 0,
        "time": 2,
        "intelligentContent": 7,
        "number_operators": 3,
        "number_operands": 4,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 70.03,
        "mIwoC": 70.03,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 4.33,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\ErrorController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 72.1,
        "mIwoC": 72.1,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Controllers\\HomeController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Views\\HomeTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendOrderEmail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 24,
        "ccn": 22,
        "ccnMethodMax": 11,
        "externals": [
            "Models\\Product",
            "Views\\OrderTemplate",
            "Services\\ValidateOrderData",
            "Models\\Product",
            "Models\\Log",
            "PHPMailer\\PHPMailer\\PHPMailer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 268,
        "vocabulary": 87,
        "volume": 1726.71,
        "difficulty": 14.26,
        "effort": 24616.96,
        "level": 0.07,
        "bugs": 0.58,
        "time": 1368,
        "intelligentContent": 121.12,
        "number_operators": 71,
        "number_operands": 197,
        "number_operators_unique": 11,
        "number_operands_unique": 76,
        "cloc": 8,
        "loc": 120,
        "lloc": 112,
        "mi": 49.14,
        "mIwoC": 29.67,
        "commentWeight": 19.47,
        "kanDefect": 1.4,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.28,
        "relativeSystemComplexity": 144.28,
        "totalStructuralComplexity": 432,
        "totalDataComplexity": 0.85,
        "totalSystemComplexity": 432.85,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Models\\Product",
            "Controllers\\ErrorController",
            "Views\\ProductTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 7,
        "volume": 36.5,
        "difficulty": 3,
        "effort": 109.49,
        "level": 0.33,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 12.17,
        "number_operators": 5,
        "number_operands": 8,
        "number_operators_unique": 3,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 63.79,
        "mIwoC": 63.79,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 9.75,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 9.75,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "requireAuth",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updatePhone",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateCard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 22,
        "ccnMethodMax": 11,
        "externals": [
            "Models\\User",
            "Views\\ProfileTemplate",
            "Models\\User",
            "Models\\User",
            "Models\\User"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 184,
        "vocabulary": 49,
        "volume": 1033.11,
        "difficulty": 10.42,
        "effort": 10761.53,
        "level": 0.1,
        "bugs": 0.34,
        "time": 598,
        "intelligentContent": 99.18,
        "number_operators": 59,
        "number_operands": 125,
        "number_operators_unique": 7,
        "number_operands_unique": 42,
        "cloc": 0,
        "loc": 112,
        "lloc": 112,
        "mi": 31.23,
        "mIwoC": 31.23,
        "commentWeight": 0,
        "kanDefect": 1.27,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 49.25,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 246.25,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\ServicesController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Views\\ServicesTemplate"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Controllers\\VerificationController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "sendCode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showVerifyPage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendVerificationEmail",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveCodeToFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 31,
        "ccn": 27,
        "ccnMethodMax": 11,
        "externals": [
            "Models\\User",
            "Models\\Log",
            "PHPMailer\\PHPMailer\\PHPMailer"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 297,
        "vocabulary": 92,
        "volume": 1937.5,
        "difficulty": 12.74,
        "effort": 24691.28,
        "level": 0.08,
        "bugs": 0.65,
        "time": 1372,
        "intelligentContent": 152.03,
        "number_operators": 88,
        "number_operands": 209,
        "number_operators_unique": 10,
        "number_operands_unique": 82,
        "cloc": 1,
        "loc": 175,
        "lloc": 174,
        "mi": 30.32,
        "mIwoC": 24.48,
        "commentWeight": 5.84,
        "kanDefect": 1.36,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 144.22,
        "totalStructuralComplexity": 720,
        "totalDataComplexity": 1.08,
        "totalSystemComplexity": 721.08,
        "package": "Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Models\\Log",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filter",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStats",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clearOld",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clearAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 27,
        "ccn": 21,
        "ccnMethodMax": 10,
        "externals": [
            "Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 248,
        "vocabulary": 73,
        "volume": 1535.08,
        "difficulty": 18.49,
        "effort": 28386.33,
        "level": 0.05,
        "bugs": 0.51,
        "time": 1577,
        "intelligentContent": 83.01,
        "number_operators": 60,
        "number_operands": 188,
        "number_operators_unique": 12,
        "number_operands_unique": 61,
        "cloc": 2,
        "loc": 105,
        "lloc": 103,
        "mi": 41.57,
        "mIwoC": 30.96,
        "commentWeight": 10.61,
        "kanDefect": 1.63,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.69,
        "relativeSystemComplexity": 121.69,
        "totalStructuralComplexity": 847,
        "totalDataComplexity": 4.83,
        "totalSystemComplexity": 851.83,
        "package": "Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrderById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 15,
        "ccnMethodMax": 9,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 84,
        "vocabulary": 27,
        "volume": 399.41,
        "difficulty": 8.93,
        "effort": 3564.74,
        "level": 0.11,
        "bugs": 0.13,
        "time": 198,
        "intelligentContent": 44.75,
        "number_operators": 33,
        "number_operands": 51,
        "number_operators_unique": 7,
        "number_operands_unique": 20,
        "cloc": 0,
        "loc": 56,
        "lloc": 56,
        "mi": 41.63,
        "mIwoC": 41.63,
        "commentWeight": 0,
        "kanDefect": 1.03,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.3,
        "relativeSystemComplexity": 4.3,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 16.5,
        "totalSystemComplexity": 21.5,
        "package": "Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getBasketData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "prepareData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 47,
        "ccn": 40,
        "ccnMethodMax": 12,
        "externals": [
            "Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 380,
        "vocabulary": 92,
        "volume": 2478.95,
        "difficulty": 18.35,
        "effort": 45497.87,
        "level": 0.05,
        "bugs": 0.83,
        "time": 2528,
        "intelligentContent": 135.07,
        "number_operators": 79,
        "number_operands": 301,
        "number_operators_unique": 10,
        "number_operands_unique": 82,
        "cloc": 7,
        "loc": 107,
        "lloc": 100,
        "mi": 46.52,
        "mIwoC": 27.23,
        "commentWeight": 19.3,
        "kanDefect": 1.56,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.22,
        "relativeSystemComplexity": 50.22,
        "totalStructuralComplexity": 392,
        "totalDataComplexity": 9.75,
        "totalSystemComplexity": 401.75,
        "package": "Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadUsers",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveUsers",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findByEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllUsers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setRole",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verifyUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updatePhone",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateCard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "verifyPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 14,
        "nbMethods": 14,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 21,
        "ccn": 8,
        "ccnMethodMax": 3,
        "externals": [
            "Database"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 169,
        "vocabulary": 46,
        "volume": 933.48,
        "difficulty": 9.83,
        "effort": 9171.46,
        "level": 0.1,
        "bugs": 0.31,
        "time": 510,
        "intelligentContent": 95.01,
        "number_operators": 38,
        "number_operands": 131,
        "number_operators_unique": 6,
        "number_operands_unique": 40,
        "cloc": 2,
        "loc": 96,
        "lloc": 94,
        "mi": 46.17,
        "mIwoC": 35.09,
        "commentWeight": 11.09,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.91,
        "relativeSystemComplexity": 50.91,
        "totalStructuralComplexity": 686,
        "totalDataComplexity": 26.75,
        "totalSystemComplexity": 712.75,
        "package": "Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "Services\\ValidateOrderData",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sanitizePhone",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrors",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 16,
        "ccnMethodMax": 15,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 126,
        "vocabulary": 32,
        "volume": 630,
        "difficulty": 14.33,
        "effort": 9030,
        "level": 0.07,
        "bugs": 0.21,
        "time": 502,
        "intelligentContent": 43.95,
        "number_operators": 40,
        "number_operands": 86,
        "number_operators_unique": 8,
        "number_operands_unique": 24,
        "cloc": 3,
        "loc": 51,
        "lloc": 48,
        "mi": 59.92,
        "mIwoC": 41.57,
        "commentWeight": 18.35,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.83,
        "relativeSystemComplexity": 2.83,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 5.5,
        "totalSystemComplexity": 8.5,
        "package": "Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Services\\ValidateRegisterData",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sanitize",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrors",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 12,
        "ccnMethodMax": 12,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 94,
        "vocabulary": 28,
        "volume": 451.89,
        "difficulty": 11,
        "effort": 4970.8,
        "level": 0.09,
        "bugs": 0.15,
        "time": 276,
        "intelligentContent": 41.08,
        "number_operators": 28,
        "number_operands": 66,
        "number_operators_unique": 7,
        "number_operands_unique": 21,
        "cloc": 4,
        "loc": 46,
        "lloc": 42,
        "mi": 66.44,
        "mIwoC": 44.39,
        "commentWeight": 22.06,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 16,
        "package": "Services\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Views\\AboutTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 2.36,
        "effort": 133.11,
        "level": 0.42,
        "bugs": 0.02,
        "time": 7,
        "intelligentContent": 23.96,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 117,
        "lloc": 114,
        "mi": 42.73,
        "mIwoC": 42.73,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\AdminTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getStyles",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dashboard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "activateAdmin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 48,
        "ccn": 43,
        "ccnMethodMax": 23,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 6,
        "length": 637,
        "vocabulary": 174,
        "volume": 4741.16,
        "difficulty": 19.01,
        "effort": 90126.67,
        "level": 0.05,
        "bugs": 1.58,
        "time": 5007,
        "intelligentContent": 249.41,
        "number_operators": 234,
        "number_operands": 403,
        "number_operators_unique": 15,
        "number_operands_unique": 159,
        "cloc": 13,
        "loc": 1013,
        "lloc": 985,
        "mi": 11.91,
        "mIwoC": 3.18,
        "commentWeight": 8.73,
        "kanDefect": 1.58,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.78,
        "relativeSystemComplexity": 6.78,
        "totalStructuralComplexity": 24,
        "totalDataComplexity": 16.67,
        "totalSystemComplexity": 40.67,
        "package": "Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\AuthTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "registerForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loginForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 11,
        "ccnMethodMax": 6,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 119,
        "vocabulary": 35,
        "volume": 610.38,
        "difficulty": 6.33,
        "effort": 3865.77,
        "level": 0.16,
        "bugs": 0.2,
        "time": 215,
        "intelligentContent": 96.38,
        "number_operators": 43,
        "number_operands": 76,
        "number_operators_unique": 5,
        "number_operands_unique": 30,
        "cloc": 0,
        "loc": 202,
        "lloc": 200,
        "mi": 28.82,
        "mIwoC": 28.82,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\BaseTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 16,
        "ccnMethodMax": 16,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 100,
        "vocabulary": 39,
        "volume": 528.54,
        "difficulty": 9.45,
        "effort": 4994.71,
        "level": 0.11,
        "bugs": 0.18,
        "time": 277,
        "intelligentContent": 55.93,
        "number_operators": 37,
        "number_operands": 63,
        "number_operators_unique": 9,
        "number_operands_unique": 30,
        "cloc": 3,
        "loc": 90,
        "lloc": 87,
        "mi": 50.43,
        "mIwoC": 36.47,
        "commentWeight": 13.95,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Views\\",
        "pageRank": 0.32,
        "afferentCoupling": 10,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Views\\BasketTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 203,
        "vocabulary": 69,
        "volume": 1240.03,
        "difficulty": 7.56,
        "effort": 9380.23,
        "level": 0.13,
        "bugs": 0.41,
        "time": 521,
        "intelligentContent": 163.93,
        "number_operators": 69,
        "number_operands": 134,
        "number_operators_unique": 7,
        "number_operands_unique": 62,
        "cloc": 19,
        "loc": 259,
        "lloc": 221,
        "mi": 46.63,
        "mIwoC": 26.26,
        "commentWeight": 20.37,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 3,
        "package": "Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\CatalogTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 150,
        "vocabulary": 56,
        "volume": 871.1,
        "difficulty": 6.79,
        "effort": 5911.06,
        "level": 0.15,
        "bugs": 0.29,
        "time": 328,
        "intelligentContent": 128.37,
        "number_operators": 55,
        "number_operands": 95,
        "number_operators_unique": 7,
        "number_operands_unique": 49,
        "cloc": 19,
        "loc": 194,
        "lloc": 173,
        "mi": 53.09,
        "mIwoC": 29.79,
        "commentWeight": 23.3,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\HomeTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 17,
        "volume": 163.5,
        "difficulty": 2.46,
        "effort": 402.91,
        "level": 0.41,
        "bugs": 0.05,
        "time": 22,
        "intelligentContent": 66.35,
        "number_operators": 17,
        "number_operands": 23,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 11,
        "loc": 464,
        "lloc": 414,
        "mi": 39.09,
        "mIwoC": 27.28,
        "commentWeight": 11.81,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\OrderTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 112,
        "vocabulary": 49,
        "volume": 628.85,
        "difficulty": 7.32,
        "effort": 4601.32,
        "level": 0.14,
        "bugs": 0.21,
        "time": 256,
        "intelligentContent": 85.94,
        "number_operators": 37,
        "number_operands": 75,
        "number_operators_unique": 8,
        "number_operands_unique": 41,
        "cloc": 3,
        "loc": 448,
        "lloc": 418,
        "mi": 28.61,
        "mIwoC": 22.28,
        "commentWeight": 6.32,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "package": "Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\ProductTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 107,
        "vocabulary": 46,
        "volume": 591.02,
        "difficulty": 6.28,
        "effort": 3712.83,
        "level": 0.16,
        "bugs": 0.2,
        "time": 206,
        "intelligentContent": 94.08,
        "number_operators": 37,
        "number_operands": 70,
        "number_operators_unique": 7,
        "number_operands_unique": 39,
        "cloc": 2,
        "loc": 106,
        "lloc": 103,
        "mi": 46.44,
        "mIwoC": 35.88,
        "commentWeight": 10.56,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "Views\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Views\\ProfileTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formatPhone",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 22,
        "ccn": 21,
        "ccnMethodMax": 19,
        "externals": [
            "Views\\BaseTemplate",
            "Models\\Order"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 2,
        "length": 271,
        "vocabulary": 95,
        "volume": 1780.43,
        "difficulty": 8.41,
        "effort": 14980.18,
        "level": 0.12,
        "bugs": 0.59,
        "time": 832,
        "intelligentContent": 211.61,
        "number_operators": 88,
        "number_operands": 183,
        "number_operators_unique": 8,
        "number_operands_unique": 87,
        "cloc": 1,
        "loc": 166,
        "lloc": 165,
        "mi": 32.04,
        "mIwoC": 26.04,
        "commentWeight": 6,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 10,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 20,
        "package": "Views\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Views\\ServicesTemplate",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Views\\BaseTemplate"
        ],
        "parents": [
            "Views\\BaseTemplate"
        ],
        "implements": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 2.36,
        "effort": 133.11,
        "level": 0.42,
        "bugs": 0.02,
        "time": 7,
        "intelligentContent": 23.96,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 570,
        "lloc": 524,
        "mi": 28.28,
        "mIwoC": 28.28,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Views\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]